### ISSUE TITLE
Problems with load maildev:1.3.0 and Cypress:12.5.1

### ISSUE THREAD

**Issue by mkonev-casafari** [Clebiez/cypress-maildev#9]
Hello,

After update to new version 1.3.0 I have faced with issue during the test starting.... config seems not be changed
Here is stacktrace of issue. I case of additional info please do not hesitate to ask me
`Oops...we found an error preparing this test file:

  > cypress/support/e2e.js

The error was:

Error: Webpack Compilation Error
/node_modules/cypress-maildev/src/index.ts 5:8
Module parse failed: Unexpected token (5:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| register(Cypress);
> declare global {
|   namespace Cypress {
|     interface Chainable {
 @ /cypress/support/e2e.js 21:0-26
    at handle (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:231:23)
    at finalCallback (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:257:39)
    at /root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:499:39)
    at /root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:298:10
    at /root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:482:27
    at /root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/neo-async/async.js:2818:7
    at done (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:464:33
    at /root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:188:23)

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.`

**Comment by Clebiez** [comment]
Yes effectively, I will work on a quick fix.
You can downgrade on the v1.2 as a temporary workaround

**Comment by Clebiez** [comment]
You can now upgrade to v1.3.1 and everything should be ok now

**Comment by mkonev-casafari** [comment]
Thanks, will check it soon
